/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rouleTokenSol from "./rouleToken.sol";
export type { rouleTokenSol };
import type * as roulefiSol from "./roulefi.sol";
export type { roulefiSol };
export type { Lock } from "./Lock";
