/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDreamToken,
  IDreamTokenInterface,
} from "../../../contracts/roulefi.sol/IDreamToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDreamToken__factory {
  static readonly abi = _abi;
  static createInterface(): IDreamTokenInterface {
    return new Interface(_abi) as IDreamTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDreamToken {
    return new Contract(address, _abi, runner) as unknown as IDreamToken;
  }
}
