/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRouleFiToken__factory } from "./IRouleFiToken__factory";
export { Roulefinance__factory } from "./Roulefinance__factory";
